/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#210e0b',
        'surface-dim': '#210e0b',
        'surface-bright': '#4c332f',
        'surface-container-lowest': '#1b0906',
        'surface-container-low': '#2b1613',
        'surface-container': '#2f1a16',
        'surface-container-high': '#3b2420',
        'surface-container-highest': '#472f2a',
        'on-surface': '#ffdad4',
        'on-surface-variant': '#e0bfb7',
        'inverse-surface': '#ffdad4',
        'inverse-on-surface': '#422a26',
        outline: '#a88a83',
        'outline-variant': '#59413b',
        'surface-tint': '#ffb4a1',
        primary: '#ffb4a1',
        'on-primary': '#611300',
        'primary-container': '#bd401e',
        'on-primary-container': '#ffe7e2',
        'inverse-primary': '#ac3412',
        secondary: '#f4be55',
        'on-secondary': '#412d00',
        'secondary-container': '#986d00',
        'on-secondary-container': '#fffbff',
        tertiary: '#cec5b9',
        'on-tertiary': '#343027',
        'tertiary-container': '#706a60',
        'on-tertiary-container': '#f4ebde',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbd2',
        'primary-fixed-dim': '#ffb4a1',
        'on-primary-fixed': '#3c0800',
        'on-primary-fixed-variant': '#891f00',
        'secondary-fixed': '#ffdea7',
        'secondary-fixed-dim': '#f4be55',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4200',
        'tertiary-fixed': '#eae1d4',
        'tertiary-fixed-dim': '#cec5b9',
        'on-tertiary-fixed': '#1f1b13',
        'on-tertiary-fixed-variant': '#4b463d',
        background: '#210e0b',
        'on-background': '#ffdad4',
        'surface-variant': '#472f2a',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        }
      }
    }
  },
  plugins: [],
};